language: cpp
sudo: false
dist: trusty
cache:
  apt: true
  directories:
    - ffmpeg-release
#    - android-ndk  # may be as slow as downloading from original source. only cache 1 platform+toolchains?
# TODO: libav

git:
  submodules: true

matrix:
  include:
    - os: osx
      compiler: clang
      osx_image: xcode8.2
      env:
        - TARGET=host
    - os: osx
      compiler: clang
      osx_image: xcode8.2
      env:
        - TARGET=iOS
    - os: linux
      compiler: gcc
      env:
        - TARGET=host
        - _CC=gcc-6 #--cc=$_CC
      addons: #can be used in matrix, but required by every combination
        apt:
          sources:
            - ubuntu-toolchain-r-test
            #- llvm-toolchain-precise-3.9
          packages:
            - gcc-6
            - p7zip-full
            - yasm
            - libva-dev
            - libvdpau-dev
            - sshpass
    - os: linux
      compiler: gcc # host compiler is not used, just to tell build script to use which compiler to use from ndk. env: CC/CXX
      env:
        - TARGET=android
      addons: #can be used in matrix, but required by every combination
        apt:
          packages:
            - p7zip-full
            - yasm
            - sshpass
    - os: linux
      compiler: clang # host compiler is not used, just to tell build script to use which compiler to use from ndk. env: CC/CXX
      env:
        - TARGET=android
      addons: #can be used in matrix, but required by every combination
        apt:
          packages:
            - p7zip-full
            - yasm
            - sshpass
# TODO: mingw64

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update --all; fi
install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install yasm perl hudochenkov/sshpass/sshpass xz; fi
  - mkdir -p ffmpeg-release
  - |
      if grep -q ${FF_VERSION} ffmpeg-release/VERSION 2>/dev/null; then
        echo "ffmpeg source exists"
      else
        wget http://ffmpeg.org/releases/ffmpeg-${FF_VERSION}.tar.bz2
        tar jxf ffmpeg-${FF_VERSION}.tar.bz2
        rm -rf ffmpeg-release
        mv ffmpeg-${FF_VERSION} ffmpeg-release
      fi
  - |
      if [ "${TARGET:0:7}" == "android" -a ! -f android-ndk/${NDK_VERSION} ]; then
        wget https://dl.google.com/android/repository/android-ndk-${NDK_VERSION}-linux-x86_64.zip
        7z x -y android-ndk-${NDK_VERSION}-linux-x86_64.zip >/dev/null
        rm -rf android-ndk
        ls -l
        mv android-ndk-${NDK_VERSION} android-ndk
        touch android-ndk/${NDK_VERSION}
      fi

script:
  - export FFSRC=$PWD/ffmpeg-release
  - export ANDROID_NDK=$PWD/android-ndk
  - if [ -n "$_CC" ]; then export USER_OPT=--cc=$_CC; fi
  - ln -sf config{-lite,}.sh
  - |
      if [ "${TARGET/-/}" == "$TARGET" ]; then
        USE_TOOLCHAIN=$CC ./avbuild.sh $TARGET  # CC(gcc/clang) is set by travis depending on compiler
      else # for TARGET=android-armv5 etc.
        USE_TOOLCHAIN=$CC ./avbuild.sh ${TARGET%%-*} "${TARGET#*-}"
      fi

after_success:
  - SUFFIX=${TARGET}
  - SUFFIX=${SUFFIX/#host/${TRAVIS_OS_NAME}}
  - SUFFIX=${SUFFIX/#osx/macOS}
  - SUFFIX=${SUFFIX/%android/$SUFFIX-$CC}
  - SUFFIX=${SUFFIX}-lite
  - mv sdk* ffmpeg-${FF_VERSION}-${SUFFIX}
  - tar Jcf ffmpeg-${FF_VERSION}-${SUFFIX}{.tar.xz,}
  - ls -hl ffmpeg-${FF_VERSION}-${SUFFIX}.tar.xz
  - sshpass -p $SF_PW scp -o StrictHostKeyChecking=no ffmpeg-${FF_VERSION}-${SUFFIX}.tar.xz $SF_USER,avbuild@frs.sourceforge.net:/home/frs/project/a/av/avbuild/${SUFFIX%%-*}

branches:
  only:
    - master
    - prelease
    - ci/travis
    - /^travis.*$/

notifications:
  email:
    recipients:
      - wbsecg1@gmail.com
    on_success: change
    on_failure: always
