branches:
  only:
    - master
    - prelease
    - ci/appveyor
    - appveyor

environment:
  matrix:
# standalone mingw32: C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0
  - _ARCH: 32
    _CC: MINGW
    _PLATFORM: desktop

  - _ARCH: 64
    _CC: MINGW
    _PLATFORM: desktop

  - _ARCH: x86
    _CC: VS2013
    _PLATFORM: desktop

  - _ARCH: x64
    _CC: VS2015
    _PLATFORM: desktop

  - _ARCH: arm
    _CC: VS2013
    _PLATFORM: phone

  - _ARCH: x64
    _CC: VS2013
    _PLATFORM: store

  - _ARCH: arm
    _CC: VS2015
    _PLATFORM: store

  - _ARCH: x64
    _CC: VS2015
    _PLATFORM: store

matrix:
  fast_finish: false

#cache:
#  - ffmpeg

init:
  - echo NUMBER_OF_PROCESSORS=%NUMBER_OF_PROCESSORS%
  - echo PROCESSOR_IDENTIFIER=%PROCESSOR_IDENTIFIER%
  - dir C:\msys64

install:
  - if /i %_ARCH%==arm git submodule update --init
  - appveyor DownloadFile "http://ffmpeg.org/releases/ffmpeg-%FF_VERSION%.tar.xz"
  - 7z x ffmpeg-%FF_VERSION%.tar.xz
  - 7z x ffmpeg-%FF_VERSION%.tar > NUL
  - move /y ffmpeg-%FF_VERSION% ffmpeg
  - appveyor DownloadFile http://www.tortall.net/projects/yasm/releases/yasm-1.3.0-win64.exe -FileName ffmpeg/yasm.exe

before_build:
  - set MSYS2_PATH_TYPE=inherit
  - set MSYS2_DIR=C:\msys64
  - set BUILD_NOW=true
  - set HOME=%CD%
  - set MSYSTEM=%_CC%%_ARCH% # ffmpeg configure refuses to build for mingw in pure msys. so we lie. MUST use upper case. ommited by msvc
  - copy /y config-lite.sh config.sh

build_script:
  - if /i %_CC%==MinGW set VC_BUILD=false
  - if /i %_CC%==MinGW %MSYS2_DIR%\usr\bin\bash.exe --login avbuild.sh
  - if /i not %_CC%==MinGW tools\vcbuild.bat %_CC% %_PLATFORM% %_ARCH%

after_build:
  - move sdk* ffmpeg-%FF_VERSION%-%_CC%-%_PLATFORM%-%_ARCH%-lite
  - 7z a ffmpeg-%FF_VERSION%-%_CC%-%_PLATFORM%-%_ARCH%-lite.7z ffmpeg-%FF_VERSION%-%_CC%-%_PLATFORM%-%_ARCH%-lite

test: off

artifacts:
  - path: 'ffmpeg*.7z'  # relative to repo root

deploy:
  provider: FTP
  protocol: sftp
  host: frs.sourceforge.net
  username: novesky
  password:
    secure: 2mQg4oxdX8S7rMJz2TCGGg==
  folder: /home/frs/project/avbuild/windows-%_PLATFORM% # why always relative path even if starts with / ? I have to make a link home/frs/project/avbuild/xxx => /home/frs/project/avbuild/xxx
  active_mode: false