branches:
  only:
    - master
    - prelease
    - ci/appveyor
    - appveyor

environment:
# win 8, 8.1, 10, uwp, phone8 sdk is available
  matrix:
# only mingw32 is available
  - arch: 32
    compiler: MinGW
    target: desktop

  - arch: x86
    compiler: VS2013
    target: desktop

  - arch: x64
    compiler: VS2015
    target: desktop

  - arch: arm
    compiler: VS2015
    target: winstore

  - arch: x64
    compiler: VS2015
    target: winstore

matrix:
  fast_finish: false

#cache:
#  - ffmpeg

init:
  - echo NUMBER_OF_PROCESSORS=%NUMBER_OF_PROCESSORS%
  - echo PROCESSOR_IDENTIFIER=%PROCESSOR_IDENTIFIER%
  - dir C:\msys64

install:
  - if %arch%==arm git submodule update --init
  - appveyor DownloadFile "http://ffmpeg.org/releases/ffmpeg-%FF_VERSION%.tar.xz"
  - 7z x ffmpeg-%FF_VERSION%.tar.xz
  - 7z x ffmpeg-%FF_VERSION%.tar > NUL
  - move /y ffmpeg-%FF_VERSION% ffmpeg
  - appveyor DownloadFile http://www.tortall.net/projects/yasm/releases/yasm-1.3.0-win64.exe -FileName ffmpeg/yasm.exe

before_build:
  - set PATH=%PATH%;C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0
  - set MSYS2_PATH_TYPE=inherit
  - set MSYS2_DIR=C:\msys64
  - set BUILD_NOW=true
  - set HOME=%CD%
  - copy /y config-lite.sh config.sh
  - dir

build_script:
  - if %compiler%==MinGW %MSYS2_DIR%\usr\bin\bash.exe --login build_ffmpeg.sh
  - if not %compiler%==MinGW tools\vcbuild.bat %compiler% %target% %arch%

after_build:
  - 7z a ffmpeg-%FF_VERSION%-%compiler%-%target%-%arch%.7z sdk-*

test: off

artifacts:
  - path: 'ffmpeg*.7z'  # relative to repo root
